---
- name: Download amazon-ssm-agent rpm
  get_url:
    url: https://s3.{{ ssmagent_region_name }}.amazonaws.com/amazon-ssm-{{ ssmagent_region_name }}/latest/linux_amd64/amazon-ssm-agent.rpm
    dest: /tmp/amazon-ssm-agent.rpm
    owner: root
    group: root
    mode: '0644'

- name: Install amazon-ssm-agent rpm
  yum:
    name: /tmp/amazon-ssm-agent.rpm
    state: present

- name: Start and enable service
  systemd:
    name: amazon-ssm-agent.service
    enabled: yes
    state: started

