# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# The purpose of this Vagrantfile is to develop/test/debug this ansible role.

# This doesn't work unless we have the vbguest plugin
unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'This Vagrantfile depends on the vagrant-vbguest plugin'
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.ssh.insert_key = false

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  config.vm.synced_folder "../", "/etc/ansible/roles/ansible-postgresql-client"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|

     # set the name of the VM
     vb.name = "centos7_test_ansible_postgresql_client"

     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end

  config.vm.provision "ansible_local" do |ansible|
     ansible.playbook = "playbook.yml"
  end

end
